[project]
name = "finales-alc-ia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.2",
    "numpy>=2.4.2",
    "pymdown-extensions>=10.21",
]
